### ISSUE TITLE
Multiple Clients- Identifying Cursors Port/IP

### ISSUE THREAD

**Issue by flbu90** [tweigel-dev/python-tuio#13]
Hi,

Im trying to create a Script where the User can choose how many clients/touch panels exsist and how they are ordered in the real world. Is there a way to identify from which IP/Port a cursor comes from?

So i can do something like:
If cursor from port = 3331: x = cursor.position x / 3        when i have 3 touch panels in a row and its the first one

**Comment by tweigel-dev** [comment]
Hay, thanks for your issue. 
I think your way to save the information which table is sending you the tuio package isn´t that simple, because the ip and port of the sender gets abstracted at the lower level dispatcher of the python-osc lib. Therefore it isn´t that simple to get ip and port.

maybe you can use the object profile or your own custom one to save an id or something else to identify the source of the bundle.

**Comment by tweigel-dev** [comment]
Did this resolve your issue ? @flbu90
